# Generated by Django 5.0.1 on 2024-03-29 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_uploadcertification_uploadcertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('verified', models.BooleanField(default=False)),
                ('school', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadid',
            name='user',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.applicant')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadCertificate',
        ),
        migrations.DeleteModel(
            name='UploadId',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
