# Generated by Django 5.0.1 on 2024-03-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_applicant_remove_uploadid_user_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='verification_code',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
