# Generated by Django 5.0.4 on 2024-05-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_applicant_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
